// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-C2wZ-uf9obdE4Qwx-Q9CokdOIMJ18YI',
    appId: '1:1025929260635:web:7bbec643ac5236d29b997e',
    messagingSenderId: '1025929260635',
    projectId: 'auth-test-b67e7',
    authDomain: 'auth-test-b67e7.firebaseapp.com',
    storageBucket: 'auth-test-b67e7.appspot.com',
    measurementId: 'G-DGY6Q3Y096',
  );
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiLp5JzunaJT5TLdyNDphvSvjeF6-zL5s',
    appId: '1:1025929260635:android:7df58fda700c8c889b997e',
    messagingSenderId: '1025929260635',
    projectId: 'auth-test-b67e7',
    storageBucket: 'auth-test-b67e7.appspot.com',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAz2UhAtcl0eT6aeN2lJfOhP1z0vPCtHDk',
    appId: '1:1025929260635:ios:c483ef6815b69e209b997e',
    messagingSenderId: '1025929260635',
    projectId: 'auth-test-b67e7',
    storageBucket: 'auth-test-b67e7.appspot.com',
    iosBundleId: 'com.example.ninemedicine',
  );
}
