// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:

      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3n3o_EXQ5Q047J6Y00cr2rnisNgPp3zE',
    appId: '1:436573396589:web:c8664116dcc81e2b916964',
    messagingSenderId: '436573396589',
    projectId: 'fir-demo-project-57fd1',
    authDomain: 'fir-demo-project-57fd1.firebaseapp.com',
    databaseURL: 'https://fir-demo-project-57fd1-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fir-demo-project-57fd1.appspot.com',
    measurementId: 'G-XMST6WE7CS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5rzvIClgP9SAFQXZjWm-wvgJ9IhxxeqY',
    appId: '1:436573396589:android:4085b9c68aecb7a9916964',
    messagingSenderId: '436573396589',
    projectId: 'fir-demo-project-57fd1',
    databaseURL: 'https://fir-demo-project-57fd1-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fir-demo-project-57fd1.appspot.com',
  );

}